name: Deploy para VPS Bagisto 2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Desabilita verificação do host SSH
      run: |
        mkdir -p ~/.ssh
        echo -e "Host *\n\tStrictHostKeyChecking no\n\tUserKnownHostsFile=/dev/null\n" > ~/.ssh/config

    - name: Deploy com rsync
      run: |
        rsync -avz --delete ./ root@31.97.172.158:/var/www/mauricio-farmacia/

    - name: Acessando a VPS e puxando alterações
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.VPS_HOST }}
        username: root
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          git config --global --add safe.directory /var/www/mauricio-farmacia
          cd /var/www/mauricio-farmacia || exit 1
          git reset --hard
          git clean -fd
          git pull origin main
          git reset --hard
          git clean -xfd
          # composer install --no-dev --optimize-autoloader
          # npm install && npm run build

          php artisan optimize:clear
          php artisan config:cache
          php artisan config:clear
          php artisan cache:clear
          php artisan route:clear
          php artisan storage:link
          php artisan view:clear
          php artisan queue:restart

          # composer install --no-dev --optimize-autoloader

